### ISSUE TITLE
The system won't boot

### ISSUE THREAD

**Issue by unsafecast** [vincenthouyi/LakeOS#3]
Hello once more (sorry for so many issues) :)

So everything built correctly, but when I type `make qemu`, it just gets stuck here:
![Screen Shot 2021-05-08 at 2 25 43 PM](https://user-images.githubusercontent.com/76212078/117537407-51e3a600-b009-11eb-976b-751ff0820b5e.png)

I waited for somewhere around 10 minutes, but nothing really happened. Note that this time I'm running on my macOS system, Big Sur.

**Comment by vincenthouyi** [comment]
Hi @unsafecast , I should appologize for making so much touble for you 😂.
I'm running the qemu on macOS Catalina 10.15.7.  Qemu version: `QEMU emulator version 4.2.0`.
There are too many reasons the kernel stuck at bootstrap. you need to connect gdb to the qemu to see where it stopped at.

you can run `make qemu-debug`, it will run qemu and wait for a gdb connection on port 1234. then you run a `aarch64-none-elf-gdb`, in gdb prompt run `file <path to kernel dir>/target/aarch64-none-elf/release/rustyl4`, then `b *0x80000`, then `target remote:1234`, and finally `continue`. then you can single step each instruction by running `stepi` and see where it hangs. 

probably you can't see the disassembled instructions because in the elf file, the bootcode is in higher half, but it hasn't jumpped to that place yet. you can see the disassembled asm by running `aarch64-none-elf-objdump -D <path to kernel dir>/target/aarch64-none-elf/release/rustyl4`, and see the assembly from `_start` symbol, and substract 0xffff0000_00000000 from the addr, you can get the real instuction running on qemu.

**Comment by unsafecast** [comment]
@vincenthouyi

> I should appologize for making so much touble for you

No you shouldn't :)

Anyway, I tried running it through GDB, and it seems to be stuck in a loop:

```
0x0000000000080020 in ?? ()
(gdb) stepi
0x0000000000080024 in ?? ()
(gdb) stepi
0x0000000000080028 in ?? ()
(gdb) stepi
0x000000000008002c in ?? ()
(gdb) stepi
0x0000000000080020 in ?? ()
(gdb) stepi
0x0000000000080024 in ?? ()
(gdb) stepi
0x0000000000080028 in ?? ()
(gdb) stepi
0x000000000008002c in ?? ()
(gdb) stepi
0x0000000000080020 in ?? ()
(gdb) stepi
0x0000000000080024 in ?? ()
(gdb) stepi
0x0000000000080028 in ?? ()
(gdb) stepi
0x000000000008002c in ?? ()
(gdb) stepi
0x0000000000080020 in ?? ()
(gdb) stepi
0x0000000000080024 in ?? ()
```

It seems to be stuck in the infinite loop from 0x0000000000080020 to 0x000000000008002c. In the object dump, those addresses are the `zero_bss_loop`:

```
ffff000000080020 <zero_bss_loop>:
ffff000000080020:       b4000082        cbz     x2, ffff000000080030 <jump_to_el1>
ffff000000080024:       f800843f        str     xzr, [x1], #8
ffff000000080028:       d1002042        sub     x2, x2, #0x8
ffff00000008002c:       b5ffffa2        cbnz    x2, ffff000000080020 <zero_bss_loop>
```

**Comment by vincenthouyi** [comment]
the zero_bss_loop will zeroing all kernel bss section. It will take a while in the loop, but it unlikely to hang. you can use `until` command of gdb to skip this part to `jump_to_el1`. In my build, this is at `0x80030`

**Comment by unsafecast** [comment]
@vincenthouyi how much does it usually take on your machine? It's taking a lot.

**Comment by vincenthouyi** [comment]
from the elf file you can see the size of bss section. in my build this is 278kb. if you single stepping the loop, it will take 34k loops. but if you simply run it, it finishes almost instantly.
